from .base import *  # noqa 403

DEBUG = True

CORS_ALLOW_ALL_ORIGINS = True

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7 * 52  # one year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_SSL_REDIRECT = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = True

REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = (  # noqa 405
    "rest_framework.renderers.JSONRenderer",
)
